// import { IDiaDiem } from "../interfaces/DiaDiem";
// import { IDonHang } from "../interfaces/DonHang";
// export const locations: IDiaDiem[] = [
//   {
//     DiaDiemId: "DD005",
//     name: "Kho Trung Tâm",
//     address: "123 Đường số 1, Linh Trung, Thủ Đức, TP.HCM",
//     district: "Thủ Đức",
//     province: "TP.HCM",
//     latitude: 10.863731,
//     longitude: 106.779495,
//   },
//   {
//     DiaDiemId: "DD006",
//     name: "Bưu Cục Quận 1",
//     address: "456 Lê Lợi, Quận 1, TP.HCM",
//     district: "Quận 1",
//     province: "TP.HCM",
//     latitude: 10.7767,
//     longitude: 106.7005,
//   },
//   {
//     DiaDiemId: "DD007",
//     name: "Bưu Cục Quận 3",
//     address: "789 Võ Văn Tần, Quận 3, TP.HCM",
//     district: "Quận 3",
//     province: "TP.HCM",
//     latitude: 10.7818,
//     longitude: 106.688,
//   },
//   {
//     DiaDiemId: "DD008",
//     name: "Bưu Cục Quận 5",
//     address: "101 Hồng Bàng, Quận 5, TP.HCM",
//     district: "Quận 5",
//     province: "TP.HCM",
//     latitude: 10.754,
//     longitude: 106.662,
//   },
//   {
//     DiaDiemId: "DD009",
//     name: "Bưu Cục Quận 7",
//     address: "202 Nguyễn Thị Thập, Quận 7, TP.HCM",
//     district: "Quận 7",
//     province: "TP.HCM",
//     latitude: 10.7238,
//     longitude: 106.7154,
//   },
// ];

// export const demoOrders: IDonHang[] = [
//   {
//     DonHangId: "DH001",
//     NhanVienId: "NV001",
//     NguoiGui: "Nguyễn Văn A",
//     NguoiNhan: "Trần Thị B",
//     SDT: "0909123456",
//     DiaChiLayHang: "123 Đường số 1, Linh Trung, Thủ Đức, TP.HCM",
//     DiaChiGiaoHang: "202 Nguyễn Thị Thập, Quận 7, TP.HCM",
//     CuocPhi: 50000,
//     TrangThai: "Chờ xử lý",
//     CreatedAt: "2025-06-22T08:00:00Z",
//     UpdatedAt: "2025-06-22T08:00:00Z",
//     GhiChu: "Giao trong giờ hành chính",
//     deliveryMethod: "Giao nhanh",
//     payer: "sender",
//     additionalServices: ["insurance", "COD"],
//     packageInfo: {
//       length: 20,
//       width: 15,
//       height: 10,
//       weight: 2,
//     },
//     packageType: "parcel",
//   },
//   {
//     DonHangId: "DH002",
//     NhanVienId: "NV002",
//     NguoiGui: "Lê Thị C",
//     NguoiNhan: "Phạm Văn D",
//     SDT: "0912345678",
//     DiaChiLayHang: "789 Võ Văn Tần, Quận 3, TP.HCM",
//     DiaChiGiaoHang: "101 Hồng Bàng, Quận 5, TP.HCM",
//     CuocPhi: 75000,
//     TrangThai: "Đang vận chuyển",
//     CreatedAt: "2025-06-21T14:00:00Z",
//     UpdatedAt: "2025-06-22T08:30:00Z",
//     GhiChu: "Liên hệ trước khi giao",
//     deliveryMethod: "Tiêu chuẩn",
//     payer: "receiver",
//     additionalServices: ["fragile"],
//     packageInfo: {
//       length: 30,
//       width: 25,
//       height: 15,
//       weight: 5,
//     },
//     packageType: "fragile",
//   },
// ];
import { IDiaDiem } from "../interfaces/DiaDiem";
import { IDonHang } from "../interfaces/DonHang";

export const locations: IDiaDiem[] = [
  {
    DiaDiemId: "DD005",
    name: "Kho Trung Tâm",
    address: "123 Đường số 1, Linh Trung, Thủ Đức, TP.HCM",
    district: "Thủ Đức",
    province: "TP.HCM",
    latitude: 10.863731,
    longitude: 106.779495,
  },
  {
    DiaDiemId: "DD006",
    name: "Bưu Cục Quận 1",
    address: "456 Lê Lợi, Quận 1, TP.HCM",
    district: "Quận 1",
    province: "TP.HCM",
    latitude: 10.7767,
    longitude: 106.7005,
  },
  {
    DiaDiemId: "DD007",
    name: "Bưu Cục Quận 3",
    address: "789 Võ Văn Tần, Quận 3, TP.HCM",
    district: "Quận 3",
    province: "TP.HCM",
    latitude: 10.7818,
    longitude: 106.688,
  },
  {
    DiaDiemId: "DD008",
    name: "Bưu Cục Quận 5",
    address: "101 Hồng Bàng, Quận 5, TP.HCM",
    district: "Quận 5",
    province: "TP.HCM",
    latitude: 10.754,
    longitude: 106.662,
  },
  {
    DiaDiemId: "DD009",
    name: "Bưu Cục Quận 7",
    address: "202 Nguyễn Thị Thập, Quận 7, TP.HCM",
    district: "Quận 7",
    province: "TP.HCM",
    latitude: 10.7238,
    longitude: 106.7154,
  },

  {
    DiaDiemId: "DD010",
    name: "Bưu Cục Quận 10",
    address: "55 Sư Vạn Hạnh, Quận 10, TP.HCM",
    district: "Quận 10",
    province: "TP.HCM",
    latitude: 10.7735,
    longitude: 106.6664,
  },
  {
    DiaDiemId: "DD011",
    name: "Bưu Cục Quận Bình Thạnh",
    address: "124 Xô Viết Nghệ Tĩnh, Bình Thạnh, TP.HCM",
    district: "Bình Thạnh",
    province: "TP.HCM",
    latitude: 10.8106,
    longitude: 106.7091,
  },
  {
    DiaDiemId: "DD012",
    name: "Bưu Cục Quận Tân Bình",
    address: "234 Hoàng Văn Thụ, Tân Bình, TP.HCM",
    district: "Tân Bình",
    province: "TP.HCM",
    latitude: 10.8014,
    longitude: 106.6525,
  },
  {
    DiaDiemId: "DD013",
    name: "Bưu Cục Quận Phú Nhuận",
    address: "78 Phan Đình Phùng, Phú Nhuận, TP.HCM",
    district: "Phú Nhuận",
    province: "TP.HCM",
    latitude: 10.7992,
    longitude: 106.6807,
  },
  {
    DiaDiemId: "DD014",
    name: "Bưu Cục Quận Gò Vấp",
    address: "12 Quang Trung, Gò Vấp, TP.HCM",
    district: "Gò Vấp",
    province: "TP.HCM",
    latitude: 10.8384,
    longitude: 106.6739,
  },
  {
    DiaDiemId: "DD015",
    name: "Bưu Cục Quận 12",
    address: "456 Tân Thới Hiệp, Quận 12, TP.HCM",
    district: "Quận 12",
    province: "TP.HCM",
    latitude: 10.8633,
    longitude: 106.6404,
  },
  {
    DiaDiemId: "DD016",
    name: "Bưu Cục Quận Tân Phú",
    address: "789 Lũy Bán Bích, Tân Phú, TP.HCM",
    district: "Tân Phú",
    province: "TP.HCM",
    latitude: 10.7906,
    longitude: 106.6282,
  },
  {
    DiaDiemId: "DD017",
    name: "Bưu Cục Quận Bình Tân",
    address: "101 Bình Long, Bình Tân, TP.HCM",
    district: "Bình Tân",
    province: "TP.HCM",
    latitude: 10.7654,
    longitude: 106.6032,
  },
  {
    DiaDiemId: "DD018",
    name: "Bưu Cục Hóc Môn",
    address: "34 Thị trấn Hóc Môn, Hóc Môn, TP.HCM",
    district: "Hóc Môn",
    province: "TP.HCM",
    latitude: 10.8833,
    longitude: 106.5898,
  },
  {
    DiaDiemId: "DD019",
    name: "Bưu Cục Củ Chi",
    address: "56 Quốc lộ 22, Củ Chi, TP.HCM",
    district: "Củ Chi",
    province: "TP.HCM",
    latitude: 11.0066,
    longitude: 106.5144,
  },
  {
    DiaDiemId: "DD020",
    name: "Bưu Cục Biên Hòa",
    address: "78 Nguyễn Ái Quốc, Biên Hòa, Đồng Nai",
    district: "Biên Hòa",
    province: "Đồng Nai",
    latitude: 10.9534,
    longitude: 106.8425,
  },
  {
    DiaDiemId: "DD021",
    name: "Bưu Cục Thủ Dầu Một",
    address: "123 Yersin, Thủ Dầu Một, Bình Dương",
    district: "Thủ Dầu Một",
    province: "Bình Dương",
    latitude: 10.9805,
    longitude: 106.6569,
  },
  {
    DiaDiemId: "DD022",
    name: "Bưu Cục Vũng Tàu",
    address: "45 Trương Công Định, Vũng Tàu, Bà Rịa - Vũng Tàu",
    district: "Vũng Tàu",
    province: "Bà Rịa - Vũng Tàu",
    latitude: 10.3459,
    longitude: 107.0843,
  },
  {
    DiaDiemId: "DD023",
    name: "Bưu Cục Long Thành",
    address: "12 Quốc lộ 51, Long Thành, Đồng Nai",
    district: "Long Thành",
    province: "Đồng Nai",
    latitude: 10.7936,
    longitude: 106.9567,
  },
  {
    DiaDiemId: "DD024",
    name: "Bưu Cục Dĩ An",
    address: "34 Đại lộ Bình Dương, Dĩ An, Bình Dương",
    district: "Dĩ An",
    province: "Bình Dương",
    latitude: 10.9076,
    longitude: 106.7694,
  },
];

export const demoOrders: IDonHang[] = [
  {
    DonHangId: "DH001",
    NhanVienId: "NV001",
    NguoiGui: "Nguyễn Văn A",
    NguoiNhan: "Trần Thị B",
    SDT: "0909123456",
    DiaChiLayHang: "123 Đường số 1, Linh Trung, Thủ Đức, TP.HCM",
    DiaChiGiaoHang: "456 Lê Lợi, Quận 1, TP.HCM",
    CuocPhi: 50000,
    TrangThai: "Chờ xử lý",
    CreatedAt: "2025-06-22T08:00:00Z",
    UpdatedAt: "2025-06-22T08:00:00Z",
    GhiChu: "Giao trong giờ hành chính",
    deliveryMethod: "Giao nhanh",
    payer: "sender",
    additionalServices: ["insurance", "COD"],
    packageInfo: {
      length: 20,
      width: 15,
      height: 10,
      weight: 2,
    },
    packageType: "parcel",
  },
  {
    DonHangId: "DH002",
    NhanVienId: "NV002",
    NguoiGui: "Lê Thị C",
    NguoiNhan: "Phạm Văn D",
    SDT: "0912345678",
    DiaChiLayHang: "789 Võ Văn Tần, Quận 3, TP.HCM",
    DiaChiGiaoHang: "101 Hồng Bàng, Quận 5, TP.HCM",
    CuocPhi: 75000,
    TrangThai: "Đang vận chuyển",
    CreatedAt: "2025-06-21T14:00:00Z",
    UpdatedAt: "2025-06-22T08:30:00Z",
    GhiChu: "Liên hệ trước khi giao",
    deliveryMethod: "Tiêu chuẩn",
    payer: "receiver",
    additionalServices: ["fragile"],
    packageInfo: {
      length: 30,
      width: 25,
      height: 15,
      weight: 5,
    },
    packageType: "fragile",
  },
  {
    DonHangId: "DH003",
    NhanVienId: "NV003",
    NguoiGui: "Trần Văn E",
    NguoiNhan: "Lê Thị F",
    SDT: "0987654321",
    DiaChiLayHang: "456 Lê Lợi, Quận 1, TP.HCM",
    DiaChiGiaoHang: "78 Nguyễn Ái Quốc, Biên Hòa, Đồng Nai",
    CuocPhi: 120000,
    TrangThai: "Chờ xử lý",
    CreatedAt: "2025-06-23T09:00:00Z",
    UpdatedAt: "2025-06-23T09:00:00Z",
    GhiChu: "Hàng dễ vỡ",
    deliveryMethod: "Liên tỉnh",
    payer: "sender",
    additionalServices: ["fragile", "insurance"],
    packageInfo: {
      length: 40,
      width: 30,
      height: 20,
      weight: 10,
    },
    packageType: "fragile",
  },
];
